Updating workflow for testing
Signed-off-by: Sakshi Bobade <sbobade@rocketsoftware.com>

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -96,6 +96,9 @@ jobs:
           export MVD_DESKTOP_DIR=zlux/zlux-app-manager/virtual-desktop
           npm run build
 
+      - name: 'Check dist exists'
+        run: ls -R dist || echo "dist not found"
+
       # note: this step is not actually doing upload to artifactory because no artifact input is provided.
       # this is just to parse and create a PUBLISH_VERSION then export, later NPM publish step can use.
       - name: '[Publish 1] Publish'
