Updating the workflow for test
Signed-off-by: Sakshi Bobade <sbobade@rocketsoftware.com>

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -97,7 +97,9 @@ jobs:
           npm run build
 
       - name: 'Check dist exists'
-        run: ls -R dist || echo "dist not found"
+        run: |
+          echo "Checking dist folder..."
+          ls -R dist || echo "dist not found"
 
       # note: this step is not actually doing upload to artifactory because no artifact input is provided.
       # this is just to parse and create a PUBLISH_VERSION then export, later NPM publish step can use.
@@ -105,7 +107,7 @@ jobs:
         uses: zowe-actions/shared-actions/publish@main
         if: success()
         with:
-          artifact-path: dist/zlux-file-explorer
+          artifacts: dist/zlux-file-explorer
           perform-release: ${{ github.event.inputs.PERFORM_RELEASE }}
           pre-release-string: ${{ github.event.inputs.PRE_RELEASE_STRING }}
 
